# Este es un archivo de configuración por defecto.
# Puede ser sobreescrito por los archivos en /configs o /experiments.
training:
  learning_rate: 0.001
  epochs: 100
  batch_size: 32

model:
  name: "gcn"
  hidden_dim: 128
  output_dim: 64
