data:
  interim_path: data/interim
  seasons:
  - 2016
  - 2017
  - 2018
  - 2019
  - 2020
  - 2021
  - 2022
  - 2023
experiment:
  description: Transformer con encoder Hybrid Graphormer-GCN (Improved)
  name: transformer_hybrid_graphormer_gcn
model:
  dropout: 0.3
  gnn_hidden: 256
  gnn_out: 256
  gnn_type: hybrid_graphormer_gcn
  heads: 8
  hidden_channels: 256
  in_channels: auto
  num_layers: 4
  out_channels: auto
  transformer_hidden: 256
  transformer_layers: 4
  type: transformer
training:
  batch_size: 1
  device: auto
  epochs: 3000
  log_interval: 100
  lr: 0.0005
  patience: 500
  save_dir: models
  save_name: transformer_hybrid_graphormer_gcn.pth
