data:
  interim_path: data/interim
  seasons:
  - 2016
  - 2017
  - 2018
  - 2019
  - 2020
  - 2021
  - 2022
  - 2023
  - 2024
experiment:
  description: Transformer con encoder Graphormer (Improved)
  name: transformer_graphormer
model:
  dropout: 0.4
  gnn_hidden: 128
  gnn_out: 128
  gnn_type: graphormer
  gnn_heads: 8
  transformer_heads: 8
  hidden_channels: 128
  in_channels: auto
  num_layers: 3
  out_channels: auto
  transformer_hidden: 128
  transformer_layers: 3
  type: transformer
training:
  batch_size: 1
  device: auto
  epochs: 3000
  log_interval: 10
  lr: 0.0003
  weight_decay: 0.001
  patience: 500
  save_dir: models
  save_name: transformer_graphormer.pth
  split_strategy: temporal
